services:
  postgres-oltp:
    image: "postgres:17.5-bullseye"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: raw
    ports: 
      - "5432:5432"
  python-backbone:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres-oltp
    volumes:
      - ./get_listings.py:/usr/local/app/get_listings.py
      - ./get_vehicle_info.py:/usr/local/app/get_vehicle_info.py
      - ./manage_zip_history.py:/usr/local/app/manage_zip_history.py
      - ./zip_codes.csv:/usr/local/app/zip_codes.csv
      - ./data:/usr/local/app/data
